### ISSUE TITLE
distribute crawl？

### ISSUE THREAD

**Issue by sakila1012** [rolando/scrapy-redis#41]
Hi, I want run this project on three machines, and share a single items queue. I don't know how to share the same redis queue?
Can you give me some suggestion？
Thank you！！！

**Comment by vaulstein** [comment]
I had tried **distributing** the request on different machines using **redis**

Below is the lines that I added in the **settings.py** file of the crawler to achieve it:

    #************* REDIS SETTINGS *********************************
    # Enables scheduling storing requests queue in redis.
    SCHEDULER = "scrapy_redis.scheduler.Scheduler"

    # Don't cleanup redis queues, allows to pause/resume crawls.
    SCHEDULER_PERSIST = True

    # Max idle time to prevent the spider from being closed when distributed crawling.
    # This only works if queue class is SpiderQueue or SpiderStack,
    # and may also block the same time when your spider start at the first time (because the queue is             empty).
    SCHEDULER_IDLE_BEFORE_CLOSE = 10

    # Specify the host and port to use when connecting to Redis (optional).
    REDIS_HOST = '111.XXX.XXX.XXX' #Redis host
    REDIS_PORT = 6379

However, you'll need to either remove `SCHEDULER_PERSIST = True` or **FLUSH** the redis queue for a new crawl, else it would not yield new links.

@rolando : Can you add a mechanism to `FLUSH` the queue when the crawl is completed so that we can pause/resume even in distributed crawling?

**Comment by rolando** [comment]
Thanks, I will look into this. Although it will be faster if you can
provide a PR :)

Rolando

**Comment by lywhlao** [comment]
I have  setted the :
REDIS_HOST = '111.XXX.XXX.XXX' #Redis host
REDIS_PORT = 6379

but when I run  process_items.py in other computer .It comes out "redis .exceptions.ConnectionEroor:Error 10061 connectin to localhost:6379"
I am confused,it seems the settins above not work.

**Comment by AllenCHM** [comment]
Hi Jason：
your need set reds host in your process_items.py.  The scraps-redis example not have set  because there are running in same computer.


发件人:  Jason Lao <notifications@github.com>
答复:  rolando/scrapy-redis <reply@reply.github.com>
日期:  2016年4月14日星期四 下午10:07
至:  rolando/scrapy-redis <scrapy-redis@noreply.github.com>
主题:  Re: [rolando/scrapy-redis] distribute crawl？ (#41)


I have  setted the :
REDIS_HOST = '111.XXX.XXX.XXX' #Redis host
REDIS_PORT = 6379

but when I run  process_items.py in other computer .It comes out "redis .exceptions.ConnectionEroor:Error 10061 connectin to localhost:6379"
I am confused,it seems the settins above not work.

**Comment by lywhlao** [comment]
Hi AllenCHM:
     Thanks very much for your answer.I have another Question: I want to make a spider like this:
     one master and N (N>1)slaves，they communicate by Redis. Master manages URLs.It put the URLs to redis queue.Slaves get the URLs,then do some work.Can you give me some directions or examples?(I was confused for several days.......)

**Comment by AllenCHM** [comment]
Hi Jason:
I’m sorry , I don’t understand what’s your mean about manages URLs. Do you have some operation like modification on your URLs queue? 

Scrapy-redis core is made requests url become distributed, it’s just have one master, if you say that redis database server is master. But role of spiders is pair. There will closed when the redis queue not have request url.


发件人:  Jason Lao <notifications@github.com>
答复:  rolando/scrapy-redis <reply@reply.github.com>
日期:  2016年4月18日星期一 下午4:11
至:  rolando/scrapy-redis <scrapy-redis@noreply.github.com>
抄送:  程传铭 <chengchuanming@hotmail.com>
主题:  Re: [rolando/scrapy-redis] distribute crawl？ (#41)


Hi AllenCHM:
 Thanks very much for your answer.I have another Question: I want to make a spider like this:
 one master and N (N>1)slaves，they communicate by Redis. Master manages URLs.It put the URLs to redis queue.Slaves get the URLs,then do some work.Can you give me some directions or examples?(I was confused for several days.......)

**Comment by avinash-mishra** [comment]
I have this problem please fix. 

$ scrapy runspider spiders/agoda_kuchikomi.py
2017-02-09 06:16:25 [scrapy.utils.log] INFO: Scrapy 1.3.0 started (bot: kuchikomi)
2017-02-09 06:16:25 [scrapy.utils.log] INFO: Overridden settings: {'AUTOTHROTTLE_DEBUG': True, 'BOT_NAME': 'kuchikomi', 'DUPEFILTER_CLASS': 'scrapy_redis.dupefilter.RFPDupeFilter', 'NEWSPIDER_MODULE': 'kuchikomi.spiders', 'SCHEDULER': 'scrapy_redis.scheduler.Scheduler', 'SPIDER_MODULES': ['kuchikomi.spiders']}
2017-02-09 06:16:25 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats', 'scrapy.extensions.logstats.LogStats']
2017-02-09 06:16:25 [agoda_kuchikomi] INFO: Reading start URLs from redis key 'agoda_kuchikomi:post' (batch size: 16, encoding: utf-8
2017-02-09 06:16:25 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
'scrapy.downloadermiddlewares.retry.RetryMiddleware',
'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-02-09 06:16:25 [scrapy.middleware] INFO: Enabled spider middlewares:
['kuchikomi.timestamp_middleware.KuchikomiSpiderMiddleware',
'scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
'scrapy.spidermiddlewares.referer.RefererMiddleware',
'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-02-09 06:16:25 [scrapy.middleware] INFO: Enabled item pipelines:
['kuchikomi.pipelines.KuchikomiPipeline']
2017-02-09 06:16:25 [scrapy.core.engine] INFO: Spider opened
Unhandled error in Deferred:
2017-02-09 06:17:25 [twisted] CRITICAL: Unhandled error in Deferred:

2017-02-09 06:17:25 [twisted] CRITICAL:
Traceback (most recent call last):
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 439, in connect
sock = self._connect()
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 494, in _connect
raise err
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 482, in _connect
sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/client.py", line 572, in execute_command
connection.send_command(*args)
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 563, in send_command
self.send_packed_command(self.pack_command(*args))
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 538, in send_packed_command
self.connect()
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 442, in connect
raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error connecting to <remote_host_ip_address>:6379. timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 439, in connect
sock = self._connect()
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 494, in _connect
raise err
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 482, in _connect
sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/Twisted-16.6.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py", line 1299, in _inlineCallbacks
result = g.send(result)
File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/crawler.py", line 74, in crawl
yield self.engine.open_spider(self.spider, start_requests)
redis.exceptions.ConnectionError: Error connecting to <remote_host_ip_address>:6379. timed out.

**Comment by laggardkernel** [comment]
@vaulstein The default queue is `PriorityQueue`, the `SCHEDULER_IDLE_BEFORE_CLOSE = 10` setting doesn't work for it.
