### ISSUE TITLE
TypeError when loading from Redis

### ISSUE THREAD

**Issue by rafaelcapucho** [rolando/scrapy-redis#49]
Hello,

The crawler is working correctly using the command `crawl` with `scrapy-redis` but when I tried to insert a job directly to redis, using `Redis Desktop Manager` like: `lpush mycrawler:start_urls http://www.epocacosmeticos.com.br/polo-red-body-spray-ralph-lauren-spray-corporal/p` I got errors:

```
2016-04-26 01:04:24 [scrapy.extensions.logstats] -> INFO: Crawled 10 pages (at 10 pages/min), scraped 0 items (at 0 items/min)
2016-04-26 01:05:24 [scrapy.extensions.logstats] -> INFO: Crawled 10 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-04-26 01:05:59 [scrapy.utils.signal] -> ERROR: Error caught on signal handler: <bound method RedisMixin.spider_idle of <EpocaCosmeticosSpider 'epocacosmeticos.com.br' at 0x7f01cdc4c438>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/scrapy/utils/signal.py", line 30, in send_catch_log
    *arguments, **named)
  File "/usr/lib/python3.5/site-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/lib/python3.5/site-packages/scrapy_redis/spiders.py", line 40, in spider_idle
    self.schedule_next_request()
  File "/usr/lib/python3.5/site-packages/scrapy_redis/spiders.py", line 34, in schedule_next_request
    req = self.next_request()
  File "/usr/lib/python3.5/site-packages/scrapy_redis/spiders.py", line 30, in next_request
    return self.make_requests_from_url(url)
  File "/usr/lib/python3.5/site-packages/scrapy/spiders/__init__.py", line 73, in make_requests_from_url
    return Request(url, dont_filter=True)
  File "/usr/lib/python3.5/site-packages/scrapy/http/request/__init__.py", line 25, in __init__
    self._set_url(url)
  File "/usr/lib/python3.5/site-packages/scrapy/http/request/__init__.py", line 51, in _set_url
    raise TypeError('Request url must be str or unicode, got %s:' % type(url).__name__)
TypeError: Request url must be str or unicode, got bytes:
2016-04-26 01:05:59 [scrapy.core.engine] -> INFO: Closing spider (finished)

```

Using `Scrapy 1.1.0rc3` and `Python 3.5.1`

Thank you

**Comment by rafaelcapucho** [comment]
Changing the file `scrapy_redis/spiders.py` in `next_request`,

from:
```
    def next_request(self):
        """Returns a request to be scheduled or none."""
        url = self.server.lpop(self.redis_key)
        if url:
            return self.make_requests_from_url(url)
```

to:
```
    def next_request(self):
        """Returns a request to be scheduled or none."""
        url = self.server.lpop(self.redis_key)
        if url:
            return self.make_requests_from_url(url.decode('utf-8'))
```

Solved the problem.
Is it a solution?
Is it still work on Py27?
Could be merged in the main branch?

Thank you

**Comment by rolando** [comment]
Thanks for your report. Python 3 (#53) is not supported yet.
