### ISSUE TITLE
builtins.TypeError: zadd() keywords must be strings

### ISSUE THREAD

**Issue by ichenfujun** [rolando/scrapy-redis#52]
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/scrapy/commands/crawl.py", line 58, in run
    self.crawler_process.start()
  File "/usr/local/lib/python3.5/site-packages/scrapy/crawler.py", line 280, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python3.5/site-packages/scrapy/utils/reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "/usr/local/lib/python3.5/site-packages/scrapy/core/engine.py", line 134, in _next_request
    self.crawl(request, spider)
  File "/usr/local/lib/python3.5/site-packages/scrapy/core/engine.py", line 209, in crawl
    self.schedule(request, spider)
  File "/usr/local/lib/python3.5/site-packages/scrapy/core/engine.py", line 215, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/usr/local/lib/python3.5/site-packages/scrapy_redis/scheduler.py", line 78, in enqueue_request
    self.queue.push(request)
  File "/usr/local/lib/python3.5/site-packages/scrapy_redis/queue.py", line 83, in push
    self.server.zadd(self.key, **pairs)
builtins.TypeError: zadd() keywords must be strings

2016-06-08 12:32:25 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/scrapy/commands/crawl.py", line 58, in run
    self.crawler_process.start()
  File "/usr/local/lib/python3.5/site-packages/scrapy/crawler.py", line 280, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/local/lib/python3.5/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python3.5/site-packages/scrapy/utils/reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "/usr/local/lib/python3.5/site-packages/scrapy/core/engine.py", line 134, in _next_request
    self.crawl(request, spider)
  File "/usr/local/lib/python3.5/site-packages/scrapy/core/engine.py", line 209, in crawl
    self.schedule(request, spider)
  File "/usr/local/lib/python3.5/site-packages/scrapy/core/engine.py", line 215, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/usr/local/lib/python3.5/site-packages/scrapy_redis/scheduler.py", line 78, in enqueue_request
    self.queue.push(request)
  File "/usr/local/lib/python3.5/site-packages/scrapy_redis/queue.py", line 83, in push
    self.server.zadd(self.key, **pairs)
builtins.TypeError: zadd() keywords must be strings

2016-06-08 12:32:30 [scrapy] INFO: Closing spider (finished)
2016-06-08 12:32:30 [scrapy] INFO: Dumping Scrapy stats:
{'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 6, 8, 4, 32, 30, 385579),
 'log_count/CRITICAL': 1,
 'log_count/INFO': 7,
 'scheduler/enqueued/redis': 1,
 'start_time': datetime.datetime(2016, 6, 8, 4, 32, 25, 376144)}
2016-06-08 12:32:30 [scrapy] INFO: Spider closed (finished)

**Comment by ichenfujun** [comment]
hi,Does scrapy_redis support Python3.x?

**Comment by rolando** [comment]
@ichenfujun not yet.

**Comment by xiangge93** [comment]
TypeError: zadd() keywords must be strings

**Comment by xiangge93** [comment]
TypeError: zadd() keywords must be strings
这个问题到底怎么修改？

**Comment by guochunyang** [comment]
@AggiWang Redis 和 StrictRedis 的 zadd 参数是相反的，后者和实际的redis命令才是完全一致的。
