### ISSUE TITLE
抓取时出现 NotImplementedError

### ISSUE THREAD

**Issue by vus520** [rolando/scrapy-redis#62]
```
2016-07-18 23:25:34 [scrapy] ERROR: Spider error processing <GET https://play.google.com/store/apps> (referer: None)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Library/Python/2.7/site-packages/Scrapy-1.1.0-py2.7.egg/scrapy/spiders/__init__.py", line 76, in parse
    raise NotImplementedError
NotImplementedErro
```

**Comment by vus520** [comment]
fixed.

sorry， 发现必须命名为
```
def parse(self, response):
```
