### ISSUE TITLE
ValueError: Function <function robo1Spider.parse.<locals>.<lambda> at 0x7f0ccc7250d0> is not a method of: <robo1Spider 'proj_20_f47c8458-705e-11e6-b152-0242ac110009' at 0x7f0d000acbe0>

### ISSUE THREAD

**Issue by wpxgit** [rolando/scrapy-redis#68]
Hi,

after enabeling scrapy-redis i got the following error:

`2016-09-01 16:13:04 [scrapy] ERROR: Spider error processing <GET https://www.domain.com/> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
GeneratorExit
Exception ignored in: <generator object iter_errback at 0x7f0cf01488b8>
RuntimeError: generator ignored GeneratorExit
Unhandled error in Deferred:
2016-09-01 16:13:04 [twisted] CRITICAL: Unhandled error in Deferred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/twisted/internet/base.py", line 1195, in run
    self.mainLoop()
  File "/usr/local/lib/python3.4/site-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.runUntilCurrent()
  File "/usr/local/lib/python3.4/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/local/lib/python3.4/site-packages/twisted/internet/task.py", line 671, in _tick
    taskObj._oneWorkUnit()
--- <exception caught here> ---
  File "/usr/local/lib/python3.4/site-packages/twisted/internet/task.py", line 517, in _oneWorkUnit
    result = next(self._iterator)
  File "/usr/local/lib/python3.4/site-packages/scrapy/utils/defer.py", line 63, in <genexpr>
    work = (callable(elem, *args, **named) for elem in iterable)
  File "/usr/local/lib/python3.4/site-packages/scrapy/core/scraper.py", line 183, in _process_spidermw_output
    self.crawler.engine.crawl(request=output, spider=spider)
  File "/usr/local/lib/python3.4/site-packages/scrapy/core/engine.py", line 209, in crawl
    self.schedule(request, spider)
  File "/usr/local/lib/python3.4/site-packages/scrapy/core/engine.py", line 215, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/usr/local/lib/python3.4/site-packages/scrapy_redis/scheduler.py", line 146, in enqueue_request
    self.queue.push(request)
  File "/usr/local/lib/python3.4/site-packages/scrapy_redis/queue.py", line 93, in push
    data = self._encode_request(request)
  File "/usr/local/lib/python3.4/site-packages/scrapy_redis/queue.py", line 36, in _encode_request
    obj = request_to_dict(request, self.spider)
  File "/usr/local/lib/python3.4/site-packages/scrapy/utils/reqser.py", line 21, in request_to_dict
    eb = _find_method(spider, eb)
  File "/usr/local/lib/python3.4/site-packages/scrapy/utils/reqser.py", line 73, in _find_method
    raise ValueError("Function %s is not a method of: %s" % (func, obj))
builtins.ValueError: Function <function robo1Spider.parse.<locals>.<lambda> at 0x7f0ccc7250d0> is not a method of: <robo1Spider 'proj_20_f47c8458-705e-11e6-b152-0242ac110009' at 0x7f0d000acbe0>
2016-09-01 16:13:04 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/twisted/internet/task.py", line 517, in _oneWorkUnit
    result = next(self._iterator)
  File "/usr/local/lib/python3.4/site-packages/scrapy/utils/defer.py", line 63, in <genexpr>
    work = (callable(elem, *args, **named) for elem in iterable)
  File "/usr/local/lib/python3.4/site-packages/scrapy/core/scraper.py", line 183, in _process_spidermw_output
    self.crawler.engine.crawl(request=output, spider=spider)
  File "/usr/local/lib/python3.4/site-packages/scrapy/core/engine.py", line 209, in crawl
    self.schedule(request, spider)
  File "/usr/local/lib/python3.4/site-packages/scrapy/core/engine.py", line 215, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/usr/local/lib/python3.4/site-packages/scrapy_redis/scheduler.py", line 146, in enqueue_request
    self.queue.push(request)
  File "/usr/local/lib/python3.4/site-packages/scrapy_redis/queue.py", line 93, in push
    data = self._encode_request(request)
  File "/usr/local/lib/python3.4/site-packages/scrapy_redis/queue.py", line 36, in _encode_request
    obj = request_to_dict(request, self.spider)
  File "/usr/local/lib/python3.4/site-packages/scrapy/utils/reqser.py", line 21, in request_to_dict
    eb = _find_method(spider, eb)
  File "/usr/local/lib/python3.4/site-packages/scrapy/utils/reqser.py", line 73, in _find_method
    raise ValueError("Function %s is not a method of: %s" % (func, obj))
ValueError: Function <function robo1Spider.parse.<locals>.<lambda> at 0x7f0ccc7250d0> is not a method of: <robo1Spider 'proj_20_f47c8458-705e-11e6-b152-0242ac110009' at 0x7f0d000acbe0>
2016-09-01 16:13:04 [scrapy] INFO: Closing spider (finished)
2016-09-01 16:13:05 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1072,
 'downloader/request_count': 4,
 'downloader/request_method_count/GET': 4,`

Python: 3.4.5
Scrapy: 1.1.2

Any hints what i can check to figure out whats wrong? Thank!

**Comment by rolando** [comment]
Looks like you are using a lambda function as a request callback. One simple solution is to use a spider method and pass arguments via request.meta.

**Comment by wpxgit** [comment]
Thanks, now it works...

**Comment by filyph** [comment]
sc

**Comment by filyph** [comment]
Hi, I am developing scrapy plugin [filyph/scrapy-sqlite](https://github.com/filyph/scrapy-sqlite) which was inspired by this plugin but works with sqlite db.

Standard scrapy.spiders.CrawlSpider uses lambdas as callbacks. Looks like problem is in request_to_dict function. Do you see any possibility how to pickle requests with lambdas?
