### ISSUE TITLE
'str' does not support the buffer interface

### ISSUE THREAD

**Issue by huansoo** [rolando/scrapy-redis#79]
2016-12-09 18:41:39 [scrapy] ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/usr/local/lib/python3.4/site-packages/scrapy_redis/spiders.py", line 84, in next_requests
    req = self.make_request_from_data(data)
  File "/usr/local/lib/python3.4/site-packages/scrapy_redis/spiders.py", line 96, in make_request_from_data
    if '://' in data:
TypeError: 'str' does not support the buffer interface

@rolando how can i do

**Comment by rolando** [comment]
You can try this PR: https://github.com/rolando/scrapy-redis/pull/71

**Comment by rolando** [comment]
Fixed in #71
