### ISSUE TITLE
[python3]TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by SiweiYang** [rolando/scrapy-redis#85]
ERROR: Error while obtaining start requests
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scrapy/core/engine.py", line 127, in _next_request
    request = next(slot.start_requests)
  File "/home/siwei/crawler/crawler/middlewares.py", line 94, in process_start_requests
    for r in start_requests:
  File "/usr/local/lib/python3.5/dist-packages/scrapy_redis/spiders.py", line 84, in next_requests
    req = self.make_request_from_data(data)
  File "/usr/local/lib/python3.5/dist-packages/scrapy_redis/spiders.py", line 96, in make_request_from_data
    if '://' in data:
TypeError: a bytes-like object is required, not 'str'

@rolando  when you retrieve "data" from redis, redis returns a byte-str by default. Decoding is necessary.

**Comment by rolando** [comment]
That was fixed in in later releases, see https://github.com/rolando/scrapy-redis/blob/v0.6.4/src/scrapy_redis/spiders.py#L109.

Could you try to install latest version?

**Comment by SiweiYang** [comment]
@rolando awesome, ty!
