### ISSUE TITLE
Distributed crawl , redis queue is not being read

### ISSUE THREAD

**Issue by avinash-mishra** [rolando/scrapy-redis#86]
My requirement is something like  [this issue](https://github.com/rolando/scrapy-redis/issues/41)

I want 3 machines 
1) Run spider 1 --> it contains scrapy only
2) Run spider 2 --> scrapy only
3) Controller --> it contains redis, scrapy-redis
spider 1 and 2 should read from redis queue of 3.  How to setup such system.

I tried  [this issue](https://github.com/rolando/scrapy-redis/issues/41) But solution is not working for me.

$ scrapy runspider spiders/agoda_kuchikomi.py
2017-02-09 06:16:25 [scrapy.utils.log] INFO: Scrapy 1.3.0 started (bot: kuchikomi)
2017-02-09 06:16:25 [scrapy.utils.log] INFO: Overridden settings: {'AUTOTHROTTLE_DEBUG': True, 'BOT_NAME': 'kuchikomi', 'DUPEFILTER_CLASS': 'scrapy_redis.dupefilter.RFPDupeFilter', 'NEWSPIDER_MODULE': 'kuchikomi.spiders', 'SCHEDULER': 'scrapy_redis.scheduler.Scheduler', 'SPIDER_MODULES': ['kuchikomi.spiders']}
2017-02-09 06:16:25 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats', 'scrapy.extensions.logstats.LogStats']
2017-02-09 06:16:25 [agoda_kuchikomi] INFO: Reading start URLs from redis key 'agoda_kuchikomi:post' (batch size: 16, encoding: utf-8
2017-02-09 06:16:25 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-02-09 06:16:25 [scrapy.middleware] INFO: Enabled spider middlewares:
['kuchikomi.timestamp_middleware.KuchikomiSpiderMiddleware',
 'scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-02-09 06:16:25 [scrapy.middleware] INFO: Enabled item pipelines:
['kuchikomi.pipelines.KuchikomiPipeline']
2017-02-09 06:16:25 [scrapy.core.engine] INFO: Spider opened
Unhandled error in Deferred:
2017-02-09 06:17:25 [twisted] CRITICAL: Unhandled error in Deferred:

2017-02-09 06:17:25 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 494, in _connect
    raise err
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error connecting to <remote_host_ip_address>:6379. timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 494, in _connect
    raise err
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/redis-2.10.5-py3.6.egg/redis/connection.py", line 482, in _connect
    sock.connect(socket_address)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/Twisted-16.6.0-py3.6-linux-x86_64.egg/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/var/users/ec2-user/.pyenv/versions/3.6.0/lib/python3.6/site-packages/scrapy/crawler.py", line 74, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
redis.exceptions.ConnectionError: Error connecting to <remote_host_ip_address>:6379. timed out.

**Comment by rolando** [comment]
Are you sure the host can connect to `<remote_host_ip_address>:6379`?

**Comment by avinash-mishra** [comment]
Actually I can not. So I have asked question on superuser http://superuser.com/questions/1177298/problems-to-connect-with-remote-redis-server
Can you help me on it ?

**Comment by avinash-mishra** [comment]
Now I can connect to <remote_host_ip_address>:6379
But problem is persistent.

**Comment by avinash-mishra** [comment]
I fixed it, problem was using public ip in aws. As I changed REDIS_HOST = <private_ip_of_AWS> problem was fixed.
Thanks for your response.
